name: Go Continuous Integration
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Run Go linters
        uses: golangci/golangci-lint-action@v3
        with:
          args: --verbose
          skip-pkg-cache: true
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Run tests
        # don't run race detector on TestRunInitCICmd because promtui package is not thread safe
        run: |
          go test -race -skip=TestRunInitCICmd ./... 
          go test -run=TestRunInitCICmd ./...
  integration-test:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.USER_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: install GitHub cli
        run: |
          sudo apt update
          sudo apt install gh -y
      - name: validate pull request is not created yet
        run: |
          PULL_REQUESTS=$(gh pr list -R ${{ secrets.TEST_REPO }} --search "'Add Atlas CI configuration' in:title" --json  headRefName | jq length)
          if [ $PULL_REQUESTS -ne 0 ]; then
              echo "Pull request already created"
              exit 1
          fi
      - name: build extension
        run: |
          go build
      - name: install extension
        run: |
          gh extension install .
      - name: run GitHub atlas extension
        run: |
          gh atlas init-ci -R ${{ secrets.TEST_REPO }} --token=${{ secrets.TEST_ATLAS_TOKEN }} --driver="sqlite" "sqlite_dir"
      - name: validate pull request is created
        uses: nick-fields/retry@v2
        with:
          timeout_seconds: 20
          retry_wait_seconds: 5
          max_attempts: 4
          command: PULL_REQUESTS=$(gh pr list -R ${{ secrets.TEST_REPO }} --search "'Add Atlas CI configuration' in:title" --json  headRefName | jq length) && [ $PULL_REQUESTS -eq 1 ]
      - name: cleanup the created pr, branch and secret
        if: always()
        run: |
          BRANCH=$(gh pr list -R ${{ secrets.TEST_REPO }} --search "'Add Atlas CI configuration' in:title" --json  headRefName | jq -r '.[0].headRefName')
          gh pr close -R ${{ secrets.TEST_REPO }} $BRANCH -d
          gh secret delete -R ${{ secrets.TEST_REPO }} ATLAS_CLOUD_TOKEN
